lang = [ 'python', 'gnuC', 'perl', 'java', 'lisp', 'fortrand' ]
print("Original order: ")
print(lang)
print("Sort list temporary: ")
print(sorted(lang))
print("Change order to reserve: ")
lang.reverse()
print(lang)
lang.sort()
print("Sort alphabetic: ")
print(lang)
print("Sort reverse: ")
lang.sort(reverse=True)
print(lang)
print("Use reverve method: ")
print(sorted(lang))
print("Original order: ")
print(lang)         
print("size of the list: ")
print(len(lang))
